apiVersion: v1
kind: Pod
metadata:
  name: blue
  labels:
    run: blue
spec:
  containers:
  - image: takeyan/flask:0.1.0
    name: flask
    env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: K8S_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
